kind: pipeline
name: default

trigger:
  branch:
    - master
    - feature/*
    - bugfix/*
    - fix/*
  event:
    - push

steps:
  - name: gomod
    image: golang:1.12
    volumes:
      - name: gopath
        path: /go
    commands:
      - GOPROXY=https://goproxy.io go mod download

  - name: gofmt
    image: golang:1.12
    volumes:
      - name: gopath
        path: /go
    commands:
      - bash -c 'count=$(go fmt ./... | wc -l);if [ $count -gt 0 ]; then exit 1; fi'

  - name: govet
    image: golang:1.12
    volumes:
      - name: gopath
        path: /go
    commands:
      - go vet ./...


  - name: golangci-lint
    image: golang:1.12
    volumes:
      - name: gopath
        path: /go
    commands:
      - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint && golangci-lint run ./...

  - name: staticcheck
    image: golang:1.12
    volumes:
      - name: gopath
        path: /go
    commands:
      - go get -u honnef.co/go/staticcheck/cmd/staticcheck && staticcheck ./...


  - name: gobuild
    image: golang:1.12
    volumes:
      - name: gopath
        path: /go
    commands:
      - go build -o agent main.go
      - cp agent /go


volumes:
  - name: gopath
    host:
      path: /tmp/drone_test