kind: pipeline
name: default

trigger:
  branch:
    - master
    - feature/*
    - bugfix/*
    - fix/*
  event:
    - push

steps:
  - name: gomod
    image: ketwang/go1.12-with-gotools
    volumes:
      - name: gopath
        path: /go
    commands:
      - GOPROXY=https://goproxy.io go mod download

  - name: gofmt
    image: ketwang/go1.12-with-gotools
    depends_on:
      - gomod
    volumes:
      - name: gopath
        path: /go
    commands:
      - bash -c 'count=$(go fmt ./... | wc -l);if [ $count -gt 0 ]; then exit 1; fi'

  - name: govet
    image: ketwang/go1.12-with-gotools
    depends_on:
      - gomod
    volumes:
      - name: gopath
        path: /go
    commands:
      - go vet ./...


  - name: golangci-lint
    image: ketwang/go1.12-with-gotools
    depends_on:
      - gomod
    volumes:
      - name: gopath
        path: /go
    commands:
      - golangci-lint run ./...

  - name: staticcheck
    image: ketwang/go1.12-with-gotools
    depends_on:
      - gomod
    volumes:
      - name: gopath
        path: /go
    commands:
      - staticcheck ./...


  - name: gobuild
    image: ketwang/go1.12-with-gotools:date
    depends_on:
      - gofmt
      - govet
      - golangci-lint
      - staticcheck
    environment:
      TZ: Asia/Shanghai
    volumes:
      - name: gopath
        path: /go
    commands:
      - CGO_ENABLED=0 bash ./script/build.sh agent
      - cp ./binaryfiles/* /go


volumes:
  - name: gopath
    host:
      path: /tmp/drone_test